# Generated by Django 2.0.10 on 2019-01-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_items_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='items',
            name='user_phone',
            field=models.IntegerField(default=0),
        ),
    ]
